# Generated by Django 4.0.2 on 2022-02-16 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='waiting',
        ),
        migrations.RemoveField(
            model_name='user',
            name='waiting_for',
        ),
    ]
