# Generated by Django 4.0.2 on 2022-02-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_notifications_obj_id_notifications_obj_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='_context',
            field=models.CharField(choices=[(1, 'react'), (2, 'follow'), (3, 'comment'), (4, 'share')], max_length=2),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='obj_type',
            field=models.CharField(choices=[(1, 'post'), (2, 'comment'), (3, 'profile')], max_length=2),
        ),
    ]
