# Generated by Django 4.0.2 on 2022-02-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('general', '0005_alter_notifications__context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='obj_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='obj_type',
        ),
        migrations.AddField(
            model_name='notifications',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
