# Generated by Django 4.0.2 on 2022-02-19 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_drag'),
        ('general', '0006_remove_notifications_obj_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notifications',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='_context',
            field=models.IntegerField(choices=[(1, 'react'), (2, 'follow')]),
        ),
    ]
