# Generated by Django 4.0.2 on 2022-02-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='user',
        ),
    ]
